name: Sync Fork

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync upstream
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git remote add upstream https://github.com/cmliu/edgetunnel.git

          git fetch upstream

          git checkout main

          git merge upstream/main --allow-unrelated-histories || true

          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
